name: Zerodha Cron Job
on:
  schedule:
    # This schedule runs every day at 20:40 IST (15:10 UTC)
    - cron: '10 15 * * *'
  workflow_dispatch: 
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Run filterData.js with env vars
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          CHARTINKEMAIL: ${{ secrets.CHARTINKEMAIL }}
          CHARTINKPASSWORD: ${{ secrets.CHARTINKPASSWORD }}
        run: node filterData.js
